/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Community;

import business.MyStringVerifier;
import business.Person;
import business.PersonDirectory;
import business.VitalSign;
import business.VitalSignHistory;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.InputVerifier;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patus
 */
public class GetAbnormalCasesByCommunity extends javax.swing.JPanel {

    /**
     * Creates new form GetAbnormalCasesByCommunity
     */
    
     private PersonDirectory personDirectory;
    private JPanel userProcessContainer;
    public GetAbnormalCasesByCommunity(JPanel userProcessContainer, PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory= personDirectory;
        InputVerifier stringVerifier = new MyStringVerifier();
//        searchBoxJTextField.setInputVerifier(stringVerifier);
        ArrayList<Person> personList = personDirectory.getPersonHistory();
        DefaultTableModel model = (DefaultTableModel) AbnormalCases.getModel();
        model.setRowCount(0);
        for(Person person: personList){
            Object[] row = new Object[3];
            row[0] = person.getPatient().getPatientID();
                                  
            row[1] = person.getPatient().getVitalSignHistory().getHistory();
//            row[1] = person.getPatient().getVitalSignHistory().getHistory().size();
            model.addRow(row);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AbnormalCases = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AbnormalCases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(AbnormalCases);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 560, 200));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AbnormalCases;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
