/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.carDetails;
import model.carDetailsHistory;

/**
 *
 * @author patus
 */
public class FirstAvailableCar extends javax.swing.JPanel {

    /**
     * Creates new form FirstAvailableCar
     */
    
    carDetailsHistory history;
    JPanel rightSplitPane;
    
    public FirstAvailableCar(carDetailsHistory history,JPanel rightSplitPane) {
        initComponents();
        this.history = history;
        this.rightSplitPane = rightSplitPane;
        getConfigFile();
//        populatetable();
//        DefaultTableModel model = (DefaultTableModel) carTable.getModel();
//        carTable.setModel(model);
//        model.addColumn("Fist Available Car");
DefaultTableModel model = (DefaultTableModel) carTable.getModel();
        TableRowSorter myTableRowSorter = new TableRowSorter(model);
        carTable.setModel(model);
        carTable.setRowSorter(myTableRowSorter);
//               
        java.util.List<RowFilter<Object,Object>> filters = new ArrayList<RowFilter<Object,Object>>(3);
//        buttonGroupAvailableCar.clearSelection();
        DefaultTableModel tblmodel = (DefaultTableModel)carTable.getModel();
        filters.add(RowFilter.regexFilter("Yes",3));
            RowFilter<Object,Object> serviceFilter = RowFilter.andFilter(filters);
            myTableRowSorter.setRowFilter(serviceFilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAvailableCar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblMaxPassengerCap = new javax.swing.JLabel();
        TxtGeoLocation = new javax.swing.JComboBox<>();
        lblModelNumber = new javax.swing.JLabel();
        TxtMaxPassengerCap = new javax.swing.JTextField();
        TxtManufacturedYear = new javax.swing.JTextField();
        TxtMinPassengerCap = new javax.swing.JTextField();
        lblCarModel = new javax.swing.JLabel();
        TxtModelNumber = new javax.swing.JTextField();
        TxtCarModel = new javax.swing.JTextField();
        lblLastMaintenanceDate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        lblManufacturedDate = new javax.swing.JLabel();
        lblCarSerialNo = new javax.swing.JLabel();
        RbAvailabilityNo = new javax.swing.JRadioButton();
        TxtManufacturedBy = new javax.swing.JTextField();
        lblGeoLocation = new javax.swing.JLabel();
        LastMaintenanceDateView = new com.toedter.calendar.JDateChooser();
        RbAvailabilityYes = new javax.swing.JRadioButton();
        lblMinPassengerCap = new javax.swing.JLabel();
        lblLastMaintenanceDate1 = new javax.swing.JLabel();
        TxtCarSerialNo = new javax.swing.JTextField();
        lblManufacturedBy = new javax.swing.JLabel();
        BtnFind = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        BackHome = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaxPassengerCap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaxPassengerCap.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMaxPassengerCap.setText("Max Passenger Capacity:");
        jPanel1.add(lblMaxPassengerCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 237, 157, -1));

        TxtGeoLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "New York City", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "Austin", "San Jose", "Fort Worth", "Jacksonville", "Columbus", "Charlotte", "Indianapolis", "San Francisco", "Seattle", "Denver", "Washington", "Boston", "El Paso", "Nashville", "Oklahoma City", "Las Vegas", "Detroit", "Portland", "Memphis", "Louisville", "Milwaukee", "Baltimore", "Albuquerque", "Tucson", "Mesa", "Fresno", "Sacramento", "Atlanta", "Kansas City", "Colorado Springs", "Raleigh", "Omaha", "Miami", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tampa", "Tulsa", "Arlington", "Wichita", "Bakersfield", "Aurora", "New Orleans", "Cleveland", "Anaheim", "Henderson", "Honolulu", "Riverside", "Santa Ana", "Corpus Christi", "Lexington", "San Juan", "Stockton", "St. Paul", "Cincinnati", "Greensboro", "Pittsburgh", "Irvine", "St. Louis", "Lincoln", "Orlando", "Durham", "Plano", "Anchorage", "Newark", "Chula Vista", "Fort Wayne", "Chandler", "Toledo", "St. Petersburg", "Reno", "Laredo", "Scottsdale", "North Las Vegas", "Lubbock", "Madison", "Gilbert", "Jersey City", "Glendale", "Buffalo", "Winston-Salem", "Chesapeake", "Fremont", "Norfolk", "Irving", "Garland", "Paradise", "Arlington", "Richmond", "Hialeah", "Boise", "Spokane", "Frisco", "Moreno Valley", "Tacoma", "Fontana", "Modesto", "Baton Rouge", "Port St. Lucie", "San Bernardino", "McKinney", "Fayetteville", "Santa Clarita", "Des Moines", "Oxnard", "Birmingham", "Spring Valley", "Huntsville", "Rochester", "Cape Coral", "Tempe", "Grand Rapids", "Yonkers", "Overland Park", "Salt Lake City", "Amarillo", "Augusta", "Columbus", "Tallahassee", "Montgomery", "Huntington Beach", "Akron", "Little Rock", "Glendale", "Grand Prairie", "Aurora", "Sunrise Manor", "Ontario", "Sioux Falls", "Knoxville", "Vancouver", "Mobile", "Worcester", "Chattanooga", "Brownsville", "Peoria", "Fort Lauderdale", "Shreveport", "Newport News", "Providence", "Elk Grove", "Rancho Cucamonga", "Salem", "Pembroke Pines", "Santa Rosa", "Eugene", "Oceanside", "Cary", "Fort Collins", "Corona", "Enterprise", "Garden Grove", "Springfield", "Clarksville", "Bayamon", "Lakewood", "Alexandria", "Hayward", "Murfreesboro", "Killeen", "Hollywood", "Lancaster", "Salinas", "Jackson", "Midland", "Macon County", "Kansas City", "Palmdale", "Sunnyvale", "Springfield", "Escondido", "Pomona", "Bellevue", "Surprise", "Naperville", "Pasadena", "Denton", "Roseville", "Joliet", "Thornton", "McAllen", "Paterson", "Rockford", "Carrollton", "Bridgeport", "Miramar", "Round Rock", "Metairie", "Olathe", "Waco" }));
        jPanel1.add(TxtGeoLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 386, 174, 30));

        lblModelNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblModelNumber.setText("Model Number:");
        jPanel1.add(lblModelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 425, 157, 21));
        jPanel1.add(TxtMaxPassengerCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 234, 174, 30));
        jPanel1.add(TxtManufacturedYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 272, 174, 30));
        jPanel1.add(TxtMinPassengerCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 191, 174, 30));

        lblCarModel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCarModel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCarModel.setText("Car Model:");
        jPanel1.add(lblCarModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 146, 157, -1));
        jPanel1.add(TxtModelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 425, 174, 30));
        jPanel1.add(TxtCarModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 143, 174, 30));

        lblLastMaintenanceDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLastMaintenanceDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastMaintenanceDate.setText("Last Maintenance Date:");
        jPanel1.add(lblLastMaintenanceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 143, 148, 20));

        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Model", "Manufacturer", "Availability", "Last Maintenance Date", "Min Pssgr", "Max Pssgr", "Manufd Year", "City", "Model No", "Date Modified"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        carTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(carTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 464, 930, 180));

        lblManufacturedDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblManufacturedDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblManufacturedDate.setText("Manufactured Year:");
        jPanel1.add(lblManufacturedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 275, 157, -1));

        lblCarSerialNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCarSerialNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCarSerialNo.setText("Car Serial Number:");
        jPanel1.add(lblCarSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 313, 157, -1));

        RbAvailabilityNo.setText("No");
        RbAvailabilityNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbAvailabilityNoActionPerformed(evt);
            }
        });
        jPanel1.add(RbAvailabilityNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 208, -1, 20));
        jPanel1.add(TxtManufacturedBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 348, 174, 30));

        lblGeoLocation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblGeoLocation.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGeoLocation.setText("Geo Location:");
        jPanel1.add(lblGeoLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 386, 157, 21));
        jPanel1.add(LastMaintenanceDateView, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 143, 148, 30));

        RbAvailabilityYes.setText("Yes");
        jPanel1.add(RbAvailabilityYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(798, 208, -1, 20));

        lblMinPassengerCap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMinPassengerCap.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMinPassengerCap.setText("Min Passenger Capacity:");
        jPanel1.add(lblMinPassengerCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 194, 157, -1));

        lblLastMaintenanceDate1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLastMaintenanceDate1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastMaintenanceDate1.setText("Available?:");
        jPanel1.add(lblLastMaintenanceDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 208, 193, 20));
        jPanel1.add(TxtCarSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 310, 174, 30));

        lblManufacturedBy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblManufacturedBy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblManufacturedBy.setText("Manufacturer By:");
        jPanel1.add(lblManufacturedBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 351, 157, -1));

        BtnFind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnFind.setText("Find");
        BtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFindActionPerformed(evt);
            }
        });
        jPanel1.add(BtnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 180, 50));

        Title.setBackground(new java.awt.Color(255, 102, 51));
        Title.setFont(new java.awt.Font("Rockwell", 1, 25)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Get First Available Car");
        Title.setOpaque(true);
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1078, 27));

        BackHome.setBackground(new java.awt.Color(255, 204, 204));
        BackHome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackHome.setText("<<Back");
        BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 116, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void carTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carTableMouseClicked
        // TODO add your handling code here:

//         buttonGroupMaintenanceCheckView.clearSelection();
        buttonGroupAvailableCar.clearSelection();
        DefaultTableModel tblmodel = (DefaultTableModel)carTable.getModel();
        
       TxtCarSerialNo.setText(tblmodel.getValueAt(carTable.getSelectedRow(),0).toString());
       TxtCarModel.setText(tblmodel.getValueAt(carTable.getSelectedRow(),1).toString());
       TxtManufacturedBy.setText(tblmodel.getValueAt(carTable.getSelectedRow(),2).toString());
//       TxtAvailability.setText(tblmodel.getValueAt(carTable.getSelectedRow(),3).toString());
        String dd = tblmodel.getValueAt(carTable.getSelectedRow(),4 ).toString();
        Date date;
        try {
            date = new SimpleDateFormat("yyyy-mm-dd").parse(dd);
            LastMaintenanceDateView.setDate(date);
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(viewJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
       
       TxtMinPassengerCap.setText(tblmodel.getValueAt(carTable.getSelectedRow(),5).toString());
       TxtMaxPassengerCap.setText(tblmodel.getValueAt(carTable.getSelectedRow(),6).toString());
       TxtManufacturedYear.setText(tblmodel.getValueAt(carTable.getSelectedRow(),7).toString());
       TxtGeoLocation.setSelectedItem(tblmodel.getValueAt(carTable.getSelectedRow(),8).toString());
       TxtModelNumber.setText(tblmodel.getValueAt(carTable.getSelectedRow(),9).toString());
//       lblDate.setText(tblmodel.getValueAt(carTable.getSelectedRow(),10).toString());
        //Availability
       String availability = tblmodel.getValueAt(carTable.getSelectedRow(),3).toString();
       
        if (availability.equals("Yes")) {
            RbAvailabilityYes.setSelected(true);
        }
        else {
            RbAvailabilityNo.setSelected(true);
        }
    }//GEN-LAST:event_carTableMouseClicked

    private void RbAvailabilityNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbAvailabilityNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbAvailabilityNoActionPerformed

    private void BtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFindActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel) carTable.getModel();
//        TableRowSorter myTableRowSorter = new TableRowSorter(model);
        carTable.setModel(tblmodel);
//        carTable.setRowSorter(myTableRowSorter);
           buttonGroupAvailableCar.clearSelection();    
//        java.util.List<RowFilter<Object,Object>> filters = new ArrayList<RowFilter<Object,Object>>(3);
//        buttonGroupAvailableCar.clearSelection();
//        DefaultTableModel tblmodel = (DefaultTableModel)carTable.getModel();
//        filters.add(RowFilter.regexFilter("Yes",3));
//            RowFilter<Object,Object> serviceFilter = RowFilter.andFilter(filters);
//            myTableRowSorter.setRowFilter(serviceFilter);
        TxtCarSerialNo.setText(carTable.getValueAt(1,1).toString());
//       for(int i = 0; i<carTable.getRowCount();i++){
//           if ((String) carTable.getValueAt(i,3) == "Yes") {
////                TxtCarSerialNo.setText("Found it!");
                TxtCarModel.setText(carTable.getValueAt(1,1).toString());
                TxtManufacturedBy.setText(carTable.getValueAt(1,2).toString());
                TxtMinPassengerCap.setText(carTable.getValueAt(1,5).toString());
                TxtMaxPassengerCap.setText(carTable.getValueAt(1,6).toString());
                TxtManufacturedYear.setText(carTable.getValueAt(1,7).toString());
                TxtGeoLocation.setSelectedItem(carTable.getValueAt(1,8).toString());
                TxtModelNumber.setText(carTable.getValueAt(1,9).toString());
                String availability = carTable.getValueAt(1,3).toString();
                if (availability.equals("Yes")) {
                    RbAvailabilityYes.setSelected(true);
                }
                else {
                    RbAvailabilityNo.setSelected(true);
                }
//                Maintenance Check
                String dd = carTable.getValueAt(1,4).toString();
                Date date;
                try {
                    date = new SimpleDateFormat("yyyy-MM-dd").parse(dd);
                    LastMaintenanceDateView.setDate(date);
                } catch (ParseException ex) {
                    Logger.getLogger(FirstAvailableCar.class.getName()).log(Level.SEVERE, null, ex);
                }
        
//                break;
//           }
           
       
        
//       }
    }//GEN-LAST:event_BtnFindActionPerformed

    private void BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHomeActionPerformed
        // TODO add your handling code here:
        searchMainJPanel BackHome = new searchMainJPanel(history, rightSplitPane);
        rightSplitPane.add("Back to Main Menu",BackHome);
        CardLayout layout = (CardLayout)rightSplitPane.getLayout();
        layout.next(rightSplitPane);
    }//GEN-LAST:event_BackHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackHome;
    private javax.swing.JButton BtnFind;
    private com.toedter.calendar.JDateChooser LastMaintenanceDateView;
    private javax.swing.JRadioButton RbAvailabilityNo;
    private javax.swing.JRadioButton RbAvailabilityYes;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TxtCarModel;
    private javax.swing.JTextField TxtCarSerialNo;
    private javax.swing.JComboBox<String> TxtGeoLocation;
    private javax.swing.JTextField TxtManufacturedBy;
    private javax.swing.JTextField TxtManufacturedYear;
    private javax.swing.JTextField TxtMaxPassengerCap;
    private javax.swing.JTextField TxtMinPassengerCap;
    private javax.swing.JTextField TxtModelNumber;
    private javax.swing.ButtonGroup buttonGroupAvailableCar;
    private javax.swing.JTable carTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarModel;
    private javax.swing.JLabel lblCarSerialNo;
    private javax.swing.JLabel lblGeoLocation;
    private javax.swing.JLabel lblLastMaintenanceDate;
    private javax.swing.JLabel lblLastMaintenanceDate1;
    private javax.swing.JLabel lblManufacturedBy;
    private javax.swing.JLabel lblManufacturedDate;
    private javax.swing.JLabel lblMaxPassengerCap;
    private javax.swing.JLabel lblMinPassengerCap;
    private javax.swing.JLabel lblModelNumber;
    // End of variables declaration//GEN-END:variables

    private void getConfigFile() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String FilePath = "C:\\Users\\patus\\Documents\\git\\PagadalaAshok_Tushar_002130680\\LabAssignment_Two\\CarData.txt";
        File file = new File(FilePath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            // get the first line
            // get the columns name from the first line
            // set columns name to the jtable model
            String firstLine = br.readLine().trim();
//            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)carTable.getModel();
//            model.setColumnIdentifiers(columnsName);
            
            // get lines from txt file
            Object[] tableLines = br.lines().toArray();
            
            // extratct data from lines
            // set data to jtable model
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                
                    model.addRow(dataRow);
                
                
                
//                carDetails cdf = getConfig.addNewCarDetailsConfig();
//                cdf.setCarModel(dataRow[i]);
//                cdf.setMinPassengerCap(Integer.parseInt(dataRow[i]));
//                cdf.setMaxPassengerCap(Integer.parseInt(dataRow[i]));
//                cdf.setManufacturedYear(Long.parseLong(dataRow[i]));
//                cdf.setCarSerialNo(Long.parseLong(dataRow[i]));
//                cdf.setManufacturedBy(dataRow[i]);
//                cdf.setGeoLocation(dataRow[i]);
//                cdf.setModelNumber(Double.parseDouble(dataRow[i]));
//                cdf.setAvailability(dataRow[i]);
//                cdf.setLastMaintenanceDate(dataRow[i]);
//                cdf.setDate(dataRow[i]);
            
            }
            
            
             
             
            
 
            
        } catch (Exception ex) {
//            Logger.getLogger(TextFileDataToJTable.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog( "File not found!");
        }


    }

    private void populatetable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        

        DefaultTableModel model = (DefaultTableModel) carTable.getModel();
//        model.setRowCount(0);
        
        for(carDetails cdh: history.getHistory()){
             Object[] row = new Object[11];
             row[0] = cdh.getCarSerialNo();
             row[1] = cdh.getCarModel();
             row[2] = cdh.getManufacturedBy();
             row[3] = cdh.getAvailability();
             row[4] = cdh.getLastMaintenanceDate();
             row[5] = cdh.getMinPassengerCap();
             row[6] = cdh.getMaxPassengerCap();
             row[7] = cdh.getManufacturedYear();
             row[8] = cdh.getGeoLocation();
             row[9] = cdh.getModelNumber();
             row[10] = cdh.getDate();
//             lblModifiedDateView.setText("Fleet Database was last updated on: "+cdh.getDate());
             model.addRow(row);
             
            
        }

////        DefaultTableModel model = (DefaultTableModel) carTable.getModel();
//        carTable.setModel(model);
        
    }


    }

