/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.carDetails;
import model.carDetailsHistory;
import java.time.LocalDate;
import java.time.Month;
import java.time.temporal.ChronoUnit;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author patus
 */
public class searchByMaintenanceCert extends javax.swing.JPanel {

    /**
     * Creates new form searchByMaintenanceCert
     */
    carDetailsHistory history;
    JPanel rightSplitPane;
    public searchByMaintenanceCert(carDetailsHistory history,JPanel rightSplitPane) {
        initComponents();
        this.history = history;
        this.rightSplitPane = rightSplitPane;
        
        getConfigFile();
//        populatetable();
        DefaultTableModel model = (DefaultTableModel) carTableCity.getModel();
        carTableCity.setModel(model);
        model.addColumn("Expired?");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        carTableCity = new javax.swing.JTable();
        BtnExpiry = new javax.swing.JButton();
        LblExpiryCount = new javax.swing.JLabel();
        BackHome = new javax.swing.JButton();
        BtnExpiry1 = new javax.swing.JButton();
        TitleCity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carTableCity.setBackground(new java.awt.Color(153, 255, 153));
        carTableCity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No", "Model", "Manufacturer", "Availability", "Maintenance?", "Min Pssgr", "Max Pssgr", "Manufd Year", "City", "Model No", "Date Modified", "Expired?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        carTableCity.setGridColor(new java.awt.Color(0, 0, 0));
        carTableCity.setSelectionBackground(new java.awt.Color(255, 204, 204));
        carTableCity.setSelectionForeground(new java.awt.Color(0, 0, 0));
        carTableCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carTableCityMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(carTableCity);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 1097, 220));

        BtnExpiry.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnExpiry.setText("Check for Expiry");
        BtnExpiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExpiryActionPerformed(evt);
            }
        });
        add(BtnExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 230, 40));

        LblExpiryCount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblExpiryCount.setForeground(new java.awt.Color(255, 255, 255));
        add(LblExpiryCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 740, 60));

        BackHome.setBackground(new java.awt.Color(255, 204, 204));
        BackHome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackHome.setText("<<Back");
        BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHomeActionPerformed(evt);
            }
        });
        add(BackHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 93, 116, 32));

        BtnExpiry1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnExpiry1.setText("Show Expired Certificates");
        BtnExpiry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExpiry1ActionPerformed(evt);
            }
        });
        add(BtnExpiry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 230, 40));

        TitleCity.setBackground(new java.awt.Color(255, 102, 51));
        TitleCity.setFont(new java.awt.Font("Rockwell", 1, 25)); // NOI18N
        TitleCity.setForeground(new java.awt.Color(255, 255, 255));
        TitleCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleCity.setText("Check for Maintenance Certificate Expiry");
        TitleCity.setOpaque(true);
        add(TitleCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, 1060, 31));
    }// </editor-fold>//GEN-END:initComponents

    private void carTableCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carTableCityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_carTableCityMouseClicked

    private void BtnExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExpiryActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) carTableCity.getModel();
        carTableCity.setModel(model);
        
        ArrayList<String> cd = new ArrayList<>();
        DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        int count = 0;
//        JOptionPane.showMessageDialog(this,getDayCount((String) model.getValueAt(1, 4),df.format(LocalDateTime.now())));
        for(int i = 0;i<model.getRowCount();i++){
            if(getDayCount((String) model.getValueAt(i, 4),df.format(LocalDateTime.now()))>180){
                model.setValueAt("Yes",i,11);
                count++;
//                System.out.println(getDayCount((String) model.getValueAt(i, 4),df.format(currentdate)));
            }else{
                model.setValueAt("No",i,11);
            }
        }
        String d1 = String.valueOf(carTableCity.getRowCount());
        LblExpiryCount.setText("Number of cars with expired Maintenance Certificates = " + count + " out of " + d1 + " Cars.");
        
        
    }//GEN-LAST:event_BtnExpiryActionPerformed

    private void BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHomeActionPerformed
        // TODO add your handling code here:
        searchMainJPanel BackHome = new searchMainJPanel(history, rightSplitPane);
        rightSplitPane.add("Back to Main Menu",BackHome);
        CardLayout layout = (CardLayout)rightSplitPane.getLayout();
        layout.next(rightSplitPane);
    }//GEN-LAST:event_BackHomeActionPerformed

    private void BtnExpiry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExpiry1ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) carTableCity.getModel();
        TableRowSorter myTableRowSorter = new TableRowSorter(model);
        carTableCity.setModel(model);
        carTableCity.setRowSorter(myTableRowSorter);
               
        java.util.List<RowFilter<Object,Object>> filters = new ArrayList<RowFilter<Object,Object>>(3);
            filters.add(RowFilter.regexFilter("Yes",11));
//            String availability = (String) DropDownAvailability.getSelectedItem();
//            filters.add(RowFilter.regexFilter("(?i)" + availability,3));
            
            RowFilter<Object,Object> serviceFilter = RowFilter.andFilter(filters);
            myTableRowSorter.setRowFilter(serviceFilter);
    }//GEN-LAST:event_BtnExpiry1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackHome;
    private javax.swing.JButton BtnExpiry;
    private javax.swing.JButton BtnExpiry1;
    private javax.swing.JLabel LblExpiryCount;
    private javax.swing.JLabel TitleCity;
    private javax.swing.JTable carTableCity;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void getConfigFile() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String FilePath = "C:\\Users\\patus\\Documents\\git\\PagadalaAshok_Tushar_002130680\\LabAssignment_Two\\CarData.txt";
        File file = new File(FilePath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            // get the first line
            // get the columns name from the first line
            // set columns name to the jtable model
//            String firstLine = br.readLine().trim();
//            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)carTableCity.getModel();
//            model.setColumnIdentifiers(columnsName);
            
            // get lines from txt file
            Object[] tableLines = br.lines().toArray();
            
            // extratct data from lines
            // set data to jtable model
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                
                    model.addRow(dataRow);
                
                
                
//                carDetails cdf = getConfig.addNewCarDetailsConfig();
//                cdf.setCarModel(dataRow[i]);
//                cdf.setMinPassengerCap(Integer.parseInt(dataRow[i]));
//                cdf.setMaxPassengerCap(Integer.parseInt(dataRow[i]));
//                cdf.setManufacturedYear(Long.parseLong(dataRow[i]));
//                cdf.setCarSerialNo(Long.parseLong(dataRow[i]));
//                cdf.setManufacturedBy(dataRow[i]);
//                cdf.setGeoLocation(dataRow[i]);
//                cdf.setModelNumber(Double.parseDouble(dataRow[i]));
//                cdf.setAvailability(dataRow[i]);
//                cdf.setLastMaintenanceDate(dataRow[i]);
//                cdf.setDate(dataRow[i]);
            
            }
            
            
             
             
            
 
            
        } catch (Exception ex) {
//            Logger.getLogger(TextFileDataToJTable.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "File not found!");
        }
    }

    private void populatetable() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
        
        DefaultTableModel model = (DefaultTableModel) carTableCity.getModel();
//        model.setRowCount(0);
        
        for(carDetails cdh: history.getHistory()){
             Object[] row = new Object[11];
             row[0] = cdh.getCarSerialNo();
             row[1] = cdh.getCarModel();
             row[2] = cdh.getManufacturedBy();
             row[3] = cdh.getAvailability();
             row[4] = cdh.getLastMaintenanceDate();
             row[5] = cdh.getMinPassengerCap();
             row[6] = cdh.getMaxPassengerCap();
             row[7] = cdh.getManufacturedYear();
             row[8] = cdh.getGeoLocation();
             row[9] = cdh.getModelNumber();
             row[10] = cdh.getDate();
//             lblModifiedDateView.setText("Fleet Database was last updated on: "+cdh.getDate());
             model.addRow(row);
             
            
        }
//        DefaultTableModel model = (DefaultTableModel) carTableCity.getModel();
//        carTableCity.setModel(model);
//        model.addColumn("Passgnr Cap?");
    
        
    }

    private int getDayCount(String start, String end) {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        LocalDate dateBefore = LocalDate.parse(start);
	LocalDate dateAfter = LocalDate.parse(end);
        int noOfDaysBetween = (int) ChronoUnit.DAYS.between(dateBefore, dateAfter);
        
        return noOfDaysBetween;
       
       
    }
}

